Export-Migration
pshdo/Rivet pull request #9
Opened 2019-05-09 15:25 UTC by splatteredbits

Created an `Export-Migration` function that exports a SQL Server database as a Rivet migration.

2019-05-09 18:37 UTC, splatteredbits commented
@webmd-health-services/devops Removed updating Whiskey from this PR. There are several tests that were migrated from Blade to Pester and their files were renamed accordingly. I wish Github showed/understood renames.

2019-05-13 19:07 UTC, decoyjoe requested changes

2019-05-13 19:07 UTC, decoyjoe commented on Rivet/Functions/Columns/New-Column.ps1
> +        # Makes the column not nullable.  Cannor be used with the `Sparse` switch.
Typo: `Cannor`

2019-05-13 19:07 UTC, decoyjoe commented on Rivet/Functions/Columns/New-Column.ps1
> +        # The size/length of the column.
This parameter doc is the exact same as `$Size`, should it rather read something like `Maximum column character length`?

2019-05-13 19:07 UTC, decoyjoe commented on Rivet/Rivet.psd1
> +* New-Column can now be used to create columns on tables that have custom size specifications, are rowguidcol, are identities, custom collations, and are file stream.
Typo: "New-Column" should have backticks around it.

2019-05-29 19:57 UTC, splatteredbits commented
@DecoyJoe Ready for another review.

2019-05-29 22:00 UTC, decoyjoe approved these changes

2019-05-29 22:12 UTC, merged